#!/bin/bash
branch=$(git rev-parse --abbrev-ref HEAD)
project_home=$(git rev-parse --show-toplevel)
mkdir -p $project_home/builds; scp $project_home/dist/js/analytique.min.js vboiteau:frontendGTI525/app/js/.
if [[ $branch != "master" ]]; then
    echo "not patching since not on master"
    exit 1
fi
npm version patch
git push
